# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94ad73d9bed7f01376da38c20502ec37319cb16a0a314a85102cecfac3a55960c83dedd10f5ae4d9705b3506fdec6734f8614dc0ed0fdad4c0471fca445f2975

test:
  secret_key_base: 07c385ed9a6b7da18406ec8b0e535f090b1a7e0273ad4c3108a3399fcac0d7fa061239f386eba451503afd840f48ec68907c9c32ed59edbc9529ded48531ab26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
